#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${RECIPE_MPR_QA_REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"

export RECIPE_MPR_QA_REPO_ROOT="${REPO_ROOT}"
export RECIPE_MPR_QA_CACHE_ROOT="${RECIPE_MPR_QA_CACHE_ROOT:-/tmp/${USER}/recipe-mpr-qa-cache}"
export RECIPE_MPR_QA_RUNTIME_ROOT="${RECIPE_MPR_QA_RUNTIME_ROOT:-${SLURM_TMPDIR:-/tmp/${USER}/recipe-mpr-qa/${SLURM_JOB_ID:-local}}}"
export RECIPE_MPR_QA_VENV_DIR="${RECIPE_MPR_QA_VENV_DIR:-${RECIPE_MPR_QA_CACHE_ROOT}/venv-cu124}"
export HF_HOME="${HF_HOME:-${RECIPE_MPR_QA_CACHE_ROOT}/hf}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}/transformers}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-${HF_HOME}/hub}"
export PIP_NO_CACHE_DIR=1
export TOKENIZERS_PARALLELISM=false
export PYTHONPATH="${REPO_ROOT}/src${PYTHONPATH:+:${PYTHONPATH}}"

mkdir -p "${REPO_ROOT}/logs" "${RECIPE_MPR_QA_CACHE_ROOT}" "${RECIPE_MPR_QA_RUNTIME_ROOT}" "${HF_HOME}"
cd "${REPO_ROOT}"
